int     clone_object(int obj, int new_zone, char *new_name);
Boolean destruct_object(int obj, Boolean *index_reused);
int     clone_mobile(int mob, int new_zone, char *new_name);
Boolean destruct_mobile(int mob, Boolean *index_reused);
int     clone_location(int l, int new_zone, char *new_name);
Boolean destruct_location(int l, Boolean *index_reused);
void    clonecom(Boolean do_brkword);
void    destructcom(char *args);
void loadcom(void);
void wizlock();
void doaction(int);
void storecom(void);
void debugcom(void);
void asmortalcom(void);
void levelscom(void);
void mailcom(void);
void promptcom(void);
void showplayer(void);
void sumcom(void);
void wavecom(void);
void forcecom(void);
void lightcom(void);
void extinguishcom(void);
void cripplecom(void);
void curecom(void);
void healcom(void);
void dumbcom(void);
void blowcom(void);
void dircom(void);
void pushcom(void);
void inviscom(void);
void viscom(void);
void deafcom(void);
void resurcom(void);
void zonescom(void);
void becom(char *args);
void rollcom(void);
void blindcom(void);
void maskcom(void);
void mflagscom(void);
void frobcom(char *args);
void emptycom(void);
void treasurecom(void);
void followcom(void);
void losecom(void);
void wishcom(void);
void lflagscom(void);
